name: seguimiento_deportes


description: Proyecto de seguimiento de deportes para gente principiante y experta.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  firebase_core: ^3.6.0       
  firebase_auth: ^5.3.1       
  cloud_firestore: ^5.4.3 
  intl: ^0.18.0 
  fl_chart: ^0.69.0
  google_sign_in: ^6.2.1

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/



  
