--DROPEAR TABLAS

DROP TABLE IF EXISTS PUBLICACIONES;
DROP TABLE IF EXISTS RUTINA_DETALLADA;
DROP TABLE IF EXISTS RUTINA_EJERCICIO;
DROP TABLE IF EXISTS RUTINA;
DROP TABLE IF EXISTS DETALLE_EJERCICIO;
DROP TABLE IF EXISTS LISTA_EJERCICIO;
DROP TABLE IF EXISTS GRUPO_MUSCULAR;
DROP TABLE IF EXISTS LOGRO_OBTENIDO;
DROP TABLE IF EXISTS LOGRO_GLOBAL;
DROP TABLE IF EXISTS OBJETIVO;
DROP TABLE IF EXISTS NOTIFICACION;
DROP TABLE IF EXISTS FEEDBACK;
DROP TABLE IF EXISTS PERFIL;
DROP TABLE IF EXISTS USUARIO;